edge-mode.indicator=normal-mode.indicator
edge-mode.mouse=normal-mode.mouse
edge-mode.press=normal-mode.press
edge-mode.release=normal-mode.release
edge-mode.toggle=normal-mode.toggle
# Invisible grid used for snapping/attaching to the screen's edges.
edge-mode.grid.area=active-screen
edge-mode.grid.area-width-percent=0.80
edge-mode.grid.area-height-percent=0.95
edge-mode.grid.row-count=1
edge-mode.grid.column-count=1
# Change line-visible to true to see the edge lines.
edge-mode.grid.line-visible=false
edge-mode.snap.up=+up | _{up} +edge
edge-mode.snap.down=+down | _{down} +edge
edge-mode.snap.left=+left | _{left} +edge
edge-mode.snap.right=+right | _{right} +edge
