grid-mode.indicator=normal-mode.indicator
grid-mode.grid.area=active-screen
grid-mode.grid.area-width-percent=0.99
grid-mode.grid.area-height-percent=0.99
grid-mode.grid.synchronization=mouse-follows-grid-center
grid-mode.grid.line-visible=true
grid-mode.grid.line-color=#FF0000
grid-mode.shrink-grid.up=+up
grid-mode.shrink-grid.down=+down
grid-mode.shrink-grid.left=+left
grid-mode.shrink-grid.right=+right
