hint1-mode.hide-cursor.enabled=true
hint1-mode.hint.type=grid
hint1-mode.hint.grid-area=active-screen
hint1-mode.hint.active-screen-grid-area-center=screen-center
hint1-mode.hint.grid-cell-width=74
hint1-mode.hint.grid-cell-height=36
hint1-mode.hint.layout-row-count=6
hint1-mode.hint.layout-column-count=5
hint1-mode.hint.selection-keys=hint1key
hint1-mode.hint.select=_{none | hint2mod} +extendedhint1key
hint1-mode.hint.font-name=Segoe UI
hint1-mode.hint.box-color=#000000 | _{hint2mod} -> #004400
hint1-mode.hint.prefix-box-enabled=true
hint1-mode.hint.prefix-in-background=true
hint1-mode.hint.prefix-font-name=Segoe UI Light
hint1-mode.hint.prefix-font-size=120
hint1-mode.hint.prefix-font-color=#FFD93D
hint1-mode.hint.prefix-selected-font-color=#CCCCCC
hint1-mode.hint.prefix-font-opacity=0.8
hint1-mode.hint.prefix-font-shadow-opacity=0
hint1-mode.hint.selected-font-opacity=0.5
# Hint configuration for a 4K screen:
hint1-mode.hint.grid-cell-width.3840x2160=96
hint1-mode.hint.grid-cell-height.3840x2160=54
hint1-mode.hint.layout-row-count.3840x2160=4
hint1-mode.hint.layout-column-count.3840x2160=10
hint1-mode.hint.selection-keys.3840x2160=extendedhint1key
# Hint configuration for a QHD screen:
hint1-mode.hint.grid-cell-width.2560x1440=64
hint1-mode.hint.grid-cell-height.2560x1440=36
hint1-mode.hint.layout-row-count.2560x1440=4
hint1-mode.hint.layout-column-count.2560x1440=10
hint1-mode.hint.selection-keys.2560x1440=extendedhint1key
# Hint configuration for a UWQHD screen:
hint1-mode.hint.grid-cell-width.3440x1440=86
hint1-mode.hint.grid-cell-height.3440x1440=36
hint1-mode.hint.layout-row-count.3440x1440=4
hint1-mode.hint.layout-column-count.3440x1440=10
hint1-mode.hint.selection-keys.3440x1440=extendedhint1key
# Prevent final hint key press from executing commands in next mode (e.g. n -> toggle left click)
hint1-mode.hint.undo=+backspace

hint2-mode.hide-cursor=hint1-mode.hide-cursor
hint2-mode.hint=hint1-mode.hint
hint2-mode.hint.type=grid
hint2-mode.hint.grid-area=active-screen
hint2-mode.hint.active-screen-grid-area-center=last-selected-hint
hint2-mode.hint.grid-max-row-count=3
hint2-mode.hint.grid-max-column-count=8
hint2-mode.hint.grid-cell-width=50
hint2-mode.hint.grid-cell-height=75
hint2-mode.hint.select=+extendedhint2key
hint2-mode.hint.selection-keys=hint2key
hint2-mode.hint.box-color=#000000
hint2-mode.hint.prefix-in-background=false
hint2-mode.hint.prefix-box-enabled=false
# Hint configuration for a 4K screen:
hint2-mode.hint.grid-max-row-count.3840x2160=4
hint2-mode.hint.grid-max-column-count.3840x2160=10
hint2-mode.hint.grid-cell-width.3840x2160=48
hint2-mode.hint.grid-cell-height.3840x2160=67.5
hint2-mode.hint.selection-keys.3840x2160=extendedhint2key
# Hint configuration for a QHD screen:
hint2-mode.hint.grid-max-row-count.2560x1440=4
hint2-mode.hint.grid-max-column-count.2560x1440=10
hint2-mode.hint.grid-cell-width.2560x1440=32
hint2-mode.hint.grid-cell-height.2560x1440=45
hint2-mode.hint.selection-keys.2560x1440=extendedhint2key
# Hint configuration for a UWQHD screen:
hint2-mode.hint.grid-max-row-count.3440x1440=4
hint2-mode.hint.grid-max-column-count.3440x1440=10
hint2-mode.hint.grid-cell-width.3440x1440=43
hint2-mode.hint.grid-cell-height.3440x1440=45
hint2-mode.hint.selection-keys.3440x1440=extendedhint2key
hint2-mode.zoom.percent=5.0
hint2-mode.zoom.center=last-selected-hint
