idle-mode.indicator.idle.edge-count=3 | _{isUppercase} -> 4
idle-mode.indicator.idle.position=center

# Outer outline
idle-mode.indicator.idle.outer-outline-thickness=3
idle-mode.indicator.idle.outer-outline-color=#FFFFFF
idle-mode.indicator.idle.outer-outline-fill-percent=0 | _{isEnter} -> 1
idle-mode.indicator.idle.outer-outline-fill-start-angle=180
idle-mode.indicator.idle.outer-outline-fill-direction=counterclockwise

# Inner outline
idle-mode.indicator.idle.inner-outline-thickness=1
idle-mode.indicator.idle.inner-outline-color=#CC0000
idle-mode.indicator.idle.inner-outline-fill-percent=1
idle-mode.indicator.idle.inner-outline-fill-start-angle=180
idle-mode.indicator.idle.inner-outline-fill-direction=counterclockwise

idle-mode.indicator.fade-animation-enabled=true
idle-mode.indicator.fade-animation-duration-millis=100
