manage-mode.indicator.idle.edge-count=5
manage-mode.indicator.idle.position=center

# Inner outline
manage-mode.indicator.idle.inner-outline-thickness=1
manage-mode.indicator.idle.inner-outline-color=#00F0F0
manage-mode.indicator.idle.inner-outline-fill-percent=1
manage-mode.indicator.idle.inner-outline-fill-start-angle=180
manage-mode.indicator.idle.inner-outline-fill-direction=both

manage-mode.indicator.fade-animation-enabled=true
manage-mode.indicator.fade-animation-duration-millis=100
