normal-mode.indicator.enabled=true
normal-mode.indicator.idle.color=#FF0000
normal-mode.indicator.move.color=#FF0000
normal-mode.indicator.wheel.color=#FFFF00
normal-mode.indicator.mouse-press.color=#00FF00

normal-mode.mouse.initial-velocity=100
normal-mode.mouse.max-velocity=2200 | _{slow} ^{superslow} -> 350 | _{fast} -> 4500 | _{superslow} -> 75
normal-mode.mouse.acceleration=3000 | _{fast} -> 5000
normal-mode.wheel.initial-velocity=1500
normal-mode.wheel.max-velocity=2000 | _{slow} ^{superslow} -> 200 | _{fast} -> 10000 | _{superslow} -> 50
normal-mode.wheel.acceleration=500 | _{fast} -> 10000

# Start moving with direction keys.
# When releasing the edge key, if direction keys are already pressed then start moving.
normal-mode.start-move.up=^{arrowmod} +up | _{up} -edge
normal-mode.start-move.down=^{arrowmod} +down | _{down} -edge
normal-mode.start-move.left=^{arrowmod} +left | _{left} -edge
normal-mode.start-move.right=^{arrowmod} +right | _{right} -edge
# Stop moving by releasing direction keys.
# If the edge/grid/hint/screenselection key is pressed, then stop moving.
normal-mode.stop-move.up=-up | #edge | +GRID | +hint | +screenselection
normal-mode.stop-move.down=-down | #edge | +GRID | +hint | +screenselection
normal-mode.stop-move.left=-left | #edge | +GRID | +hint | +screenselection
normal-mode.stop-move.right=-right | #edge | +GRID | +hint | +screenselection

# Register leftctrl to allow ctrl-clicking.
normal-mode.press.left=_{none | leftctrl} +leftbutton | _{none | leftctrl} +clickthendisable
normal-mode.press.middle=+middlebutton
normal-mode.press.right=_{none | leftctrl} +rightbutton
normal-mode.release.left=-leftbutton
normal-mode.release.middle=-middlebutton
normal-mode.release.right=-rightbutton
normal-mode.toggle.left=_{none | leftctrl} +LEFTMOUSELOCK
normal-mode.start-wheel.up=+wheelup
normal-mode.start-wheel.down=+wheeldown
normal-mode.start-wheel.left=+wheelleft
normal-mode.start-wheel.right=+wheelright
normal-mode.stop-wheel.up=-wheelup
normal-mode.stop-wheel.down=-wheeldown
normal-mode.stop-wheel.left=-wheelleft
normal-mode.stop-wheel.right=-wheelright
