numpad-mode.indicator.enabled=true
numpad-mode.indicator.idle.color=#a44545
numpad-mode.indicator.unhandled-key-press.color=#0000FF
numpad-mode.indicator.idle.size=12
numpad-mode.indicator.idle.edge-count=4
numpad-mode.indicator.idle.position=bottom-right
numpad-mode.indicator.idle.opacity=1.0 | _{rightHandNumbers} -> 0.7
