screen-selection-mode.hint.type=grid
screen-selection-mode.hint.grid-area=all-screens
screen-selection-mode.hint.grid-max-row-count=1
screen-selection-mode.hint.grid-max-column-count=1
screen-selection-mode.hint.selection-keys=hintscreenselectionkey
screen-selection-mode.hint.font-size=120
