ui-mode.indicator=normal-mode.indicator
ui-mode.hint.type=ui
ui-mode.hint.selection-keys=hint1key
ui-mode.hint.select=+hint1key
ui-mode.hint.undo=+backspace
ui-mode.hint.font-size=10
ui-mode.hint.font-weight=bold
ui-mode.hint.font-color=#FFFFFF
ui-mode.hint.selected-font-color=#CCCCCC
ui-mode.hint.font-shadow-opacity=0
ui-mode.hint.box-color=#204E8A
ui-mode.hint.box-opacity=1
ui-mode.hint.cell-horizontal-padding=8
ui-mode.hint.cell-vertical-padding=0
ui-mode.hint.box-border-opacity=1
ui-mode.hint.box-border-radius=3
ui-mode.hint.background-opacity=0.2
