window-mode.indicator=normal-mode.indicator
window-mode.grid.area=active-window
# Top inset to be able to quickly access a window's title bar (and potentially grab it and move the window).
window-mode.grid.area-top-inset=15
window-mode.grid.synchronization=mouse-follows-grid-center
window-mode.grid.row-count=1
window-mode.grid.column-count=1
window-mode.grid.line-visible=true
window-mode.grid.line-color=#FF0000
window-mode.snap.up=+up
window-mode.snap.down=+down
window-mode.snap.left=+left
window-mode.snap.right=+right
window-mode.move-to-grid-center=+grid
