# mousemaster will automatically convert the key aliases to your current keyboard layout.
# However, if you want to make a change to the key aliases, and your keyboard layout
# is not us-qwerty, then remove .us-qwerty
# key-alias.enablemod.us-qwerty=leftalt
key-alias.META=leftwin
key-alias.EXIT=capslock
key-alias.GRID=g
key-alias.UI=f
key-alias.UNDO=backspace rightalt

key-alias.LEFT_MOUSE_LOCK=space
key-alias.INPUT_BACKSPACE=rightalt

key-alias.uikey=w e r t a s d g z x c v y u i o p h j k l ; n m , . /

key-alias.clickthendisable=.
key-alias.up=k
key-alias.down=j
key-alias.left=h
key-alias.right=l
key-alias.edge=rightalt
key-alias.wheelup=,
key-alias.wheeldown=m
key-alias.wheelleft=u
key-alias.wheelright=o
key-alias.leftbutton=;
key-alias.rightbutton=' '
key-alias.middlebutton=rightshift
key-alias.fast=v b
key-alias.slow=leftshift
key-alias.superslow=capslock
key-alias.windowmod=leftshift
key-alias.hint=b
key-alias.hint2mod=leftshift
key-alias.uihintmod=leftalt
key-alias.screenselection=c
key-alias.navigateback=p
key-alias.navigateforward=n
key-alias.hint1key=q w e r t a s d f g z x c v b y u i o p h j k l ; n m , . /
key-alias.hint2key=q w e r u i o p a s d f j k l ; z x c v m , . /
key-alias.extendedhint1key=1 2 3 4 5 6 7 8 9 0 q w e r t y u i o p a s d f g h j k l ; z x c v b n m , . /
key-alias.extendedhint2key=1 2 3 4 5 6 7 8 9 0 q w e r t y u i o p a s d f g h j k l ; z x c v b n m , . /
key-alias.hintscreenselectionkey=j k l ; a s d f g
key-alias.arrowmod=leftalt
key-alias.arrowkey=up down left right

key-alias.arrowextramod=leftshift leftctrl leftwin
