# mousemaster will automatically convert the key aliases to your current keyboard layout.
# However, if you want to make a change to the key aliases, and your keyboard layout
# is not us-qwerty, then remove .us-qwerty
# key-alias.enablemod.us-qwerty=leftalt
key-alias.enablekey.us-qwerty=leftwin
key-alias.exit.us-qwerty=q
key-alias.clickthendisable.us-qwerty=.
key-alias.up.us-qwerty=k
key-alias.down.us-qwerty=j
key-alias.left.us-qwerty=h
key-alias.right.us-qwerty=l
key-alias.edge.us-qwerty=rightalt
key-alias.wheelup.us-qwerty=,
key-alias.wheeldown.us-qwerty=m
key-alias.wheelleft.us-qwerty=u
key-alias.wheelright.us-qwerty=o
key-alias.leftbutton.us-qwerty=;
key-alias.rightbutton.us-qwerty=' '
key-alias.middlebutton.us-qwerty=rightshift
key-alias.toggleleft.us-qwerty=n
key-alias.fast.us-qwerty=v b
key-alias.slow.us-qwerty=leftshift
key-alias.superslow.us-qwerty=capslock
key-alias.grid.us-qwerty=g
key-alias.windowmod.us-qwerty=leftshift
key-alias.hint.us-qwerty=f
key-alias.hint2mod.us-qwerty=leftshift
key-alias.uihintmod.us-qwerty=leftalt
key-alias.screenselection.us-qwerty=c
key-alias.navigateback.us-qwerty=p
key-alias.navigateforward.us-qwerty=n
key-alias.hint1key.us-qwerty=q w e r t a s d f g z x c v b y u i o p h j k l ; n m , . /
key-alias.hint2key.us-qwerty=q w e r u i o p a s d f j k l ; z x c v m , . /
key-alias.extendedhint1key.us-qwerty=1 2 3 4 5 6 7 8 9 0 q w e r t y u i o p a s d f g h j k l ; z x c v b n m , . /
key-alias.extendedhint2key.us-qwerty=1 2 3 4 5 6 7 8 9 0 q w e r t y u i o p a s d f g h j k l ; z x c v b n m , . /
key-alias.hintscreenselectionkey.us-qwerty=j k l ; a s d f g
key-alias.arrowmod.us-qwerty=leftalt
key-alias.arrowkey.us-qwerty=up down left right

key-alias.arrowextramod=leftshift leftctrl leftwin
