#********
#* IDLE *
#********
# capslock: long press -> ctrl, short tap -> esc
# link:
idle-mode.macro.caps-hold=+capslock +!capslock -!capslock -> +leftctrl +!capslock -!capslock
idle-mode.macro.caps-tap=+capslock #!capslock? -capslock -> +esc -esc
idle-mode.macro.caps-release=-capslock -> -leftctrl

idle-mode.macro.backspace_to_menu=+backspace -> +menu -menu
idle-mode.macro.Ralt_to_backspace_down=+rightalt -> +backspace
idle-mode.macro.Ralt_to_backspace_up=-rightalt -> -backspace

# FIX
# idle-mode.macro.move_left=_{capslock} +h -> leftarrow
# idle-mode.macro.move_right=_{capslock} +l -> rightarrow
# idle-mode.macro.move_up=_{capslock} +k -> uparrow
# idle-mode.macro.move_down=_{capslock} +j -> downarrow

#**********
#* normal *
#**********
normal-mode.macro.navigateback=+navigateback -> +leftalt +leftarrow -leftarrow -leftalt
normal-mode.macro.navigateforward=+navigateforward -> +leftalt +rightarrow -rightarrow -leftalt

#**********
#* numpad *
#**********
key-alias.rightHandNumbers=u i o h j k l m , .
numpad-mode.macro.numbers=+rightHandNumbers -> rightHandNumbers=7 8 9 0 4 5 6 1 2 3 -> +rightHandNumbers -rightHandNumbers
key-alias.operators1.us-qwerty=a f
key-alias.operators2=s d g
numpad-mode.macro.operators1.us-qwerty=+operators1 -> operators1== 8 -> +leftshift +operators1 -operators1 -leftshift
numpad-mode.macro.operators2=+operators2 -> operators2=minus / . -> +operators2 -operators2

idle-mode.macro=_arrowremapping-mode.macro
normal-mode.macro=_arrowremapping-mode.macro

_arrowremapping-mode.macro.pressarrow=\
  +arrowmod {#*arrowextramod?} +arrowkey | _{arrowmod | arrowmod arrowextramod} +arrowkey \
  -> arrowkey=uparrow downarrow leftarrow rightarrow \
  -> -arrowmod +arrowkey
_arrowremapping-mode.macro.releasearrow=_{arrowmod} -arrowkey \
  -> arrowkey=uparrow downarrow leftarrow rightarrow \
  -> -arrowkey
_arrowremapping-mode.macro.releaseallarrows=_{arrowkey} -arrowmod -> -uparrow -leftarrow -downarrow -rightarrow
key-alias.arrowhandledkey=arrowkey arrowextramod
_arrowremapping-mode.macro.repressalt=_{arrowmod} ^{arrowkey} #!arrowhandledkey -> +arrowmod
