function Merge-VSCodeJsoncFragments {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$PartsDir,

        [Parameter(Mandatory = $true)]
        [string]$TargetFile,

        [Parameter(Mandatory = $true)]
        [ValidateSet("Object", "Array")]
        [string]$Mode,

        [Parameter(Mandatory = $true)]
        [string]$GeneratorName,

        [Parameter(Mandatory = $true)]
        [string]$FragmentKind
    )

    if (!(Test-Path $PartsDir)) {
        throw "分片目录不存在: $PartsDir"
    }

    $files = Get-ChildItem -Path $PartsDir -Filter *.jsonc | Sort-Object Name
    if ($files.Count -eq 0) {
        throw "未找到任何 $FragmentKind 分片文件: $PartsDir"
    }

    if ($Mode -eq "Object") {
        $openToken = "{"
        $closeToken = "}"
        $outputOpen = "{"
        $outputClose = "}"
    }
    else {
        $openToken = "["
        $closeToken = "]"
        $outputOpen = "["
        $outputClose = "]"
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("// ============================================================================")
    $lines.Add("// AUTO-GENERATED BY chezmoi $GeneratorName")
    $lines.Add("// DO NOT EDIT THIS FILE DIRECTLY. EDIT FILES IN $FragmentKind/*.jsonc INSTEAD.")
    $lines.Add("// Supports: comments, mark:, #region folding blocks")
    $lines.Add("// ============================================================================")
    $lines.Add($outputOpen)

    for ($i = 0; $i -lt $files.Count; $i++) {
        $file = $files[$i]
        $name = $file.Name

        # Read raw JSONC and preserve comments.
        $raw = Get-Content -Path $file.FullName -Raw -Encoding UTF8

        # Remove UTF-8 BOM when present.
        if ($raw.Length -gt 0 -and $raw[0] -eq [char]0xFEFF) {
            $raw = $raw.Substring(1)
        }

        # Extract inner content from the outer object/array wrapper.
        $start = $raw.IndexOf($openToken)
        $end = $raw.LastIndexOf($closeToken)
        if ($start -lt 0 -or $end -le $start) {
            throw "分片文件不是有效 $Mode 结构: $name"
        }

        $body = $raw.Substring($start + 1, $end - $start - 1).Trim()

        $lines.Add("")
        $lines.Add("  // #region [source: $name]")
        $lines.Add("  // MARK: from file -> $name")

        if (![string]::IsNullOrWhiteSpace($body)) {
            $bodyLines = $body -split "`r?`n"
            foreach ($line in $bodyLines) {
                $lines.Add("  $line")
            }
        }

        $lines.Add("  // #endregion [source: $name]")

        if ($i -lt $files.Count - 1) {
            $lines.Add("  ,")
        }
    }

    $lines.Add($outputClose)

    $output = [string]::Join("`r`n", $lines)
    Set-Content -Path $TargetFile -Value $output -Encoding UTF8 -NoNewline

    Write-Host "✅ 合并完成，共处理 $($files.Count) 个分片文件。"
}
